package com.kith.core.designsystem.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext

private val DarkColorScheme = darkColorScheme(
    primary = PrimaryBlue,
    onPrimary = White,
    primaryContainer = PrimaryContainerDark,
    onPrimaryContainer = OnPrimaryContainerDark,
    secondary = SecondaryBlue,
    onSecondary = White,
    secondaryContainer = SecondaryContainerDark,
    onSecondaryContainer = OnSecondaryContainerDark,
    tertiary = LightBlue,
    onTertiary = Black,
    background = BackgroundDark,
    onBackground = White,
    surface = SurfaceDark,
    onSurface = White,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    outline = OutlineDark,
    outlineVariant = OutlineVariantDark,
    error = ErrorRed,
    onError = White,
)

private val LightColorScheme = lightColorScheme(
    primary = PrimaryBlue,
    onPrimary = White,
    primaryContainer = PrimaryContainerLight,
    onPrimaryContainer = OnPrimaryContainerLight,
    secondary = SecondaryBlue,
    onSecondary = White,
    secondaryContainer = SecondaryContainerLight,
    onSecondaryContainer = OnSecondaryContainerLight,
    tertiary = LightBlue,
    onTertiary = White,
    background = BackgroundLight,
    onBackground = DarkNavy,
    surface = SurfaceLight,
    onSurface = DarkNavy,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight,
    error = ErrorRed,
    onError = White,
)

@Composable
fun KithTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    disableDynamicTheming: Boolean = true,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        // 2. Dynamic color logic (keep your existing logic here)
        !disableDynamicTheming && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }
        // 3. Fallback to KITH custom colors based strictly on the darkTheme boolean
        darkTheme -> DarkColorScheme // Your existing KITH dark colors
        else -> LightColorScheme // Your existing KITH light colors
    }

    val extendedColors = if (darkTheme) {
        KithExtendedColors(
            authBackground = Color(0xFF101318),
            authTitleColor = Color.White,
            authDesignColor = colorScheme.tertiary,
            authWaveColor = Color(0xFF101318),
            authWaveBackgroundColor = Color(0xFF101318),
            tabTrackBg = Color(0xFF1E293B),
            tabPillBg = Color(0xFF334155),
            tabTextSelected = White,
            tabTextUnselected = Color(0xFF94A3B8),
            paywallBg = BackgroundDark,
            paywallTextPrimary = White,
            paywallTextSecondary = Color(0xFF94A3B8),
            paywallPillTrackBg = Color(0xFF1E293B),
            paywallPillTrackBorder = Color(0xFF334155),
            dailyRewardBg = DarkNavy,
            dailyRewardAccent = Color(0xFF00E5FF),
            dailyRewardTextPrimary = White,
            dailyRewardTextSecondary = Color(0xFF94A3B8),
            dailyRewardCenterCircle = DarkNavy,
            dailyRewardRingTrack = Color(0xFF1E293B),
            dailyRewardButtonBg = White,
            dailyRewardButtonText = DarkNavy,
            dailyRewardIconFuture = White.copy(alpha = 0.3f),
            historyCardBg = Color(0xFF1E293B),
            historyCardBorder = Color(0xFF334155),
            historyTitleText = White,
            historySubtitleText = Color(0xFF94A3B8),
            historyTimeText = Color(0xFF64748B),
            historyBadgeActiveBg = Color(0xFF1E3A8A).copy(alpha = 0.5f),
            historyBadgeActiveText = Color(0xFF60A5FA),
            historyBadgeInactiveBg = Color(0xFF78350F).copy(alpha = 0.5f),
            historyBadgeInactiveText = Color(0xFFFBBF24),
            historyXpActiveText = Color(0xFF94A3B8),
            historyXpInactiveText = Color(0xFF60A5FA),
            transactionCardBg = Color(0xFF1E293B),
            transactionCardBorder = Color(0xFF334155),
            transactionTitleText = White,
            transactionDateText = Color(0xFF94A3B8),
            transactionPositiveBg = Color(0xFF064E3B).copy(alpha = 0.6f),
            transactionPositiveText = Color(0xFF34D399),
            transactionNegativeBg = Color(0xFF7F1D1D).copy(alpha = 0.6f),
            transactionNegativeText = Color(0xFFF87171),
            profileBg = BackgroundDark,
            profileCardBg = SurfaceDark,
            profileCardBorder = OutlineDark,
            profileTextPrimary = White,
            profileTextSecondary = Color(0xFF94A3B8),
            profileDivider = Color(0xFF334155),
            profileIconNeutral = Color(0xFF64748B),
            profileRatingStar = Color(0xFFFBBF24),
            profileActionBlue = Color(0xFF60A5FA),
            profileActionBlueBg = Color(0xFF1E3A8A).copy(alpha = 0.3f),
            profileProBadgeBg = PrimaryBlue,
            profileProBadgeText = White,
            profileLogoutBg = Color(0xFF7F1D1D).copy(alpha = 0.2f),
            profileLogoutBorder = Color(0xFF991B1B),
            profileLogoutText = Color(0xFFF87171),
            postCardStar = Color(0xFFFBBF24),
            postCardRatingText = Color(0xFF94A3B8),
            postCardBadgeBg = Color(0xFF1E3A8A).copy(alpha = 0.3f),
            postCardBadgeText = Color(0xFF93C5FD),
            postCardContentText = Color(0xFF94A3B8),
            postCardDateText = Color(0xFF64748B),
            detailBg = BackgroundDark,
            detailTextPrimary = White,
            detailTextSecondary = Color(0xFF94A3B8),
            detailCardBg = SurfaceDark,
            detailStar = Color(0xFFFBBF24),
            detailTagBg = Color(0xFF1E3A8A).copy(alpha = 0.3f),
            detailTagText = Color(0xFF93C5FD),
            detailBountyBg = Color(0xFF1E3A8A).copy(alpha = 0.2f),
            detailBountyBorder = Color(0xFF1E40AF),
            detailBountyTitle = Color(0xFF60A5FA),
            detailBountyXp = Color(0xFF3B82F6),
            detailPrimaryBlue = PrimaryBlue,
            detailSolutionBg = Color(0xFF1E293B),
            detailBorderLight = Color(0xFF334155),
            communityBg = BackgroundDark,
            communityCardBg = SurfaceDark,
            communityCardBorder = OutlineDark,
            communityTextPrimary = White,
            communityTextSecondary = Color(0xFF94A3B8),
            communityActionBg = Color(0xFF1E3A8A).copy(alpha = 0.3f),
            communityActionIcon = Color(0xFF60A5FA),
            communityImagePlaceholderBg = Color(0xFF1E293B),
            communityImagePlaceholderIcon = Color(0xFF64748B),
            communityIconSecondary = Color(0xFF94A3B8),
            communityDangerBg = Color(0xFF7F1D1D).copy(alpha = 0.3f),
            communityDangerText = Color(0xFFF87171),
        )
    } else {
        KithExtendedColors(
            authBackground = colorScheme.tertiary,
            authTitleColor = Color.Black,
            authDesignColor = colorScheme.tertiary,
            authWaveColor = colorScheme.tertiary,
            authWaveBackgroundColor = Color.White,
            tabTrackBg = Color(0xFFF1F5F9),
            tabPillBg = White,
            tabTextSelected = PrimaryBlue,
            tabTextUnselected = Color(0xFF64748B),
            paywallBg = BackgroundLight,
            paywallTextPrimary = Color(0xFF111827),
            paywallTextSecondary = Color(0xFF6B7280),
            paywallPillTrackBg = Color(0xFFF3F4F6),
            paywallPillTrackBorder = Color(0xFFE5E7EB),
            dailyRewardBg = PrimaryBlue,
            dailyRewardAccent = DarkNavy,
            dailyRewardTextPrimary = DarkNavy,
            dailyRewardTextSecondary = DarkNavy.copy(alpha = 0.7f),
            dailyRewardCenterCircle = White,
            dailyRewardRingTrack = White.copy(alpha = 0.3f),
            dailyRewardButtonBg = DarkNavy,
            dailyRewardButtonText = White,
            dailyRewardIconFuture = DarkNavy.copy(alpha = 0.3f),
            historyCardBg = White,
            historyCardBorder = Color(0xFFE2E8F0),
            historyTitleText = Color(0xFF0F172A),
            historySubtitleText = Color(0xFF64748B),
            historyTimeText = Color(0xFF94A3B8),
            historyBadgeActiveBg = Color(0xFFEFF6FF),
            historyBadgeActiveText = Color(0xFF3B82F6),
            historyBadgeInactiveBg = Color(0xFFFFFBEB),
            historyBadgeInactiveText = Color(0xFFD97706),
            historyXpActiveText = Color(0xFF64748B),
            historyXpInactiveText = Color(0xFF3B82F6),
            transactionCardBg = White,
            transactionCardBorder = Color(0xFFF0F0F0),
            transactionTitleText = Color(0xFF1A1A1A),
            transactionDateText = Color.Gray,
            transactionPositiveBg = Color(0xFFE6F4EA),
            transactionPositiveText = Color(0xFF137333),
            transactionNegativeBg = Color(0xFFFCE8E6),
            transactionNegativeText = Color(0xFFC5221F),
            profileBg = Color(0xFFF8F9FA),
            profileCardBg = White,
            profileCardBorder = Color(0xFFF0F0F0),
            profileTextPrimary = Color.Black,
            profileTextSecondary = Color(0xFF64748B),
            profileDivider = Color(0xFFE2E8F0),
            profileIconNeutral = Color(0xFF94A3B8),
            profileRatingStar = Color(0xFFF59E0B),
            profileActionBlue = Color(0xFF3B82F6),
            profileActionBlueBg = Color(0xFFEFF6FF),
            profileProBadgeBg = Color(0xFF3B82F6),
            profileProBadgeText = White,
            profileLogoutBg = Color(0xFFFEF2F2),
            profileLogoutBorder = Color(0xFFFCA5A5),
            profileLogoutText = Color(0xFFEF4444),
            postCardStar = Color(0xFFFDB814),
            postCardRatingText = Color.Gray,
            postCardBadgeBg = Color(0xFFEEF2FF),
            postCardBadgeText = Color(0xFF5B8DF9),
            postCardContentText = Color.Gray,
            postCardDateText = Color.LightGray,
            detailBg = White,
            detailTextPrimary = Color(0xFF111827),
            detailTextSecondary = Color(0xFF4B5563),
            detailCardBg = Color(0xFFF3F4F6),
            detailStar = Color(0xFFF59E0B),
            detailTagBg = Color(0xFFEFF4FF),
            detailTagText = Color(0xFF6366F1),
            detailBountyBg = Color(0xFFF0F4FF),
            detailBountyBorder = Color(0xFFA5B4FC),
            detailBountyTitle = Color(0xFF4F46E5),
            detailBountyXp = Color(0xFF3B82F6),
            detailPrimaryBlue = Color(0xFF2563EB),
            detailSolutionBg = Color(0xFFF7F6FB),
            detailBorderLight = Color(0xFFE5E7EB),
            communityBg = White,
            communityCardBg = White,
            communityCardBorder = Color(0xFFECEDF3),
            communityTextPrimary = Color(0xFF1B1F3B),
            communityTextSecondary = Color(0xFFA0A3B1),
            communityActionBg = Color(0xFFEFF6FF),
            communityActionIcon = Color(0xFF2563EB),
            communityImagePlaceholderBg = Color(0xFFE3E6F0),
            communityImagePlaceholderIcon = Color(0xFFA0A3B1),
            communityIconSecondary = Color(0xFFB9BCC9),
            communityDangerBg = Color(0xFFFAD9D9),
            communityDangerText = Color(0xFFD64545),
        )
    }

    CompositionLocalProvider(LocalKithExtendedColors provides extendedColors) {
        MaterialTheme(
            colorScheme = colorScheme,
            typography = Typography,
            content = content,
        )
    }
}

object KithTheme {
    val extendedColors: KithExtendedColors
        @Composable
        get() = LocalKithExtendedColors.current
}